[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pacman_game = "DRUiH1Vd6zUvrZXKmKPwKnYq8jLiUYJdffStA1ETmc2v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "custom"
wallet = "~/.config/solana/id.json"

[provider.cluster]
custom = "https://staging-rpc.dev2.eclipsenetwork.xyz"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
