[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pacman_game = "DjUfeeJXsQHPd811GHmhB6zVraAyBBVzv365BA8Ruf8T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
